apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: navidrome-music-pvc

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.storage.music.size }}

  storageClassName: manual
